DEPLOY: Error al actualizar.
2026-04-06 15:52:17,988 41 ERROR binaural-dev-crumar-staging-30557530 odoo.tools.convert: The XML file '/home/odoo/src/user/odoo-venezuela/l10n_ve_stock_account/wizard/picking_invoice_wizard.xml' does not fit the required schema!
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 731, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/etree.pyx", line 3648, in lxml.etree._Validator.assert_
AssertionError: Element odoo has extra content: record, line 3

Lo volvi en sintaxis record y elimine

        <field name="binding_view_types">list</field>