MIG #61475: l10n_ve_invoice
Problema:
-Al correr pruebas unitarias para probar las caracteristicas migradas, mostraba el siguiente error.

RPC_ERROR

Odoo Server Error

Occured on localhost on model res.config.settings on 2025-12-14 17:25:33 GMT

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2275, in _serve_db
    return service_model.retrying(serve_func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 184, in retrying
    result = func()
             ^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2330, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2545, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 357, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 788, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 32, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in call_kw
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 1960, in onchange
    defaults = self.default_get(missing_names)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 244, in default_get
    classified = self._get_classified_fields(fields)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 215, in _get_classified_fields
    groups.append((name, field_groups, ref(field.implied_group)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 195, in ref
    return self.env[res_model].browse(res_id)
           ~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/orm/environments.py", line 107, in __getitem__
    return self.registry[model_name](self, (), ())
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/odoo/orm/registry.py", line 322, in __getitem__
    return self.models[model_name]
           ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: False

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost/web/assets/fb4d179/web.assets_web.min.js:762:101)
        at App.handleError (http://localhost/web/assets/fb4d179/web.assets_web.min.js:1420:29)
        at ComponentNode.initiateRender (http://localhost/web/assets/fb4d179/web.assets_web.min.js:854:19)

Caused by: RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost/web/assets/fb4d179/web.assets_web.min.js:3186:165)
        at XMLHttpRequest.<anonymous> (http://localhost/web/assets/fb4d179/web.assets_web.min.js:3192:13)

Solución:
-Al hacer un exhautivo análisis, se logra encontrar que la raíz del problema es que hacía falta en el manifest, agregar el archivo que contiene los grupos de seguridad de l10n_ve_invoice.

Tarea (Link):
https://binaural.odoo.com/web#id=61475&cids=2&menu_id=975&action=341&model=project.task&view_type=form

Tarea de proyecto [x]
Ticket de soporte []