[FIX] Issue#1: l10n_ve_base
OwlError: Invalid props for component 'SettingsApp': 'slots' is missing (should be a object)

El error se origina debido a que
app debe contener un block y a su vez su setting.

Se crearon sus etiquetas basicas para evitar su error